// The privacy page and terms, in English and Polish: only what GDPR Article 13 and the Polish
// Act on Providing Services by Electronic Means require. Static, trusted HTML.
export const LEGAL = {
  "privacy": {
    "en": {
      "title": "Privacy",
      "html": "<h2>Who is responsible</h2>\n<div class=\"box\">\n<p><strong>Łukasz Bondarewicz</strong><br>ul. Spółdzielcza 9A/11, 78-400 Szczecinek, Poland<br>CEIDG, NIP 6731637301<br>Email: <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a></p>\n</div>\n\n<h2>What I collect</h2>\n<p>When you use the AI assistant or the contact form:</p>\n<ul>\n<li>your questions and the assistant's answers;</li>\n<li>anything you choose to share, such as your name, email address, company or role;</li>\n<li>your IP address, approximate location (country, and city where available), browser, screen size, language, time zone and the page that referred you.</li>\n</ul>\n<p>Giving your contact details is voluntary; without them I can't reply to you.</p>\n\n<h2>Why, and on what legal basis</h2>\n<ul>\n<li>To answer your questions: my legitimate interest in presenting my work to people who ask about it (GDPR Article 6(1)(f)).</li>\n<li>To reply to you when you leave your contact details: steps you ask for before a possible contract (Article 6(1)(b)).</li>\n<li>To protect the assistant from abuse: my legitimate interest in security (Article 6(1)(f)).</li>\n<li>To improve the assistant's answers: my legitimate interest (Article 6(1)(f)).</li>\n</ul>\n\n<h2>Who receives it</h2>\n<p>Service providers that process it for me: hosting and database, network and security, an AI model provider (conversation text only), a monitoring and testing tool (conversation text only), and email delivery.</p>\n<p>Some are based outside the European Economic Area, mainly in the United States. Those transfers rely on the EU-US Data Privacy Framework or on the European Commission's standard contractual clauses.</p>\n\n<h2>How long I keep it</h2>\n<ul>\n<li>Conversations: 180 days.</li>\n<li>Contact details: as long as needed to follow up with you.</li>\n<li>Copies used for monitoring and testing: as long as needed to improve the assistant.</li>\n</ul>\n\n<h2>Your rights</h2>\n<p>You can ask me to see, correct or delete your data, limit how I use it, or send you a copy, and you can object at any time to how I use it. Email <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a>.</p>\n<p>You can also complain to a data protection authority, such as UODO in Poland (<a href=\"https://uodo.gov.pl\">uodo.gov.pl</a>).</p>"
    },
    "pl": {
      "title": "Prywatność",
      "html": "<h2>Administrator danych</h2>\n<div class=\"box\">\n<p><strong>Łukasz Bondarewicz</strong><br>ul. Spółdzielcza 9A/11, 78-400 Szczecinek<br>CEIDG, NIP 6731637301<br>E-mail: <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a></p>\n</div>\n\n<h2>Jakie dane zbieram</h2>\n<p>Gdy korzystasz z asystenta AI lub formularza kontaktowego:</p>\n<ul>\n<li>Twoje pytania i odpowiedzi asystenta;</li>\n<li>informacje, które zdecydujesz się podać, np. imię i nazwisko, adres e-mail, firmę lub stanowisko;</li>\n<li>adres IP, przybliżoną lokalizację (kraj oraz, jeśli jest dostępne, miasto), przeglądarkę, rozmiar ekranu, język, strefę czasową i stronę, z której przyszedłeś.</li>\n</ul>\n<p>Podanie danych kontaktowych jest dobrowolne; bez nich nie mogę Ci odpowiedzieć.</p>\n\n<h2>Cele i podstawy prawne</h2>\n<ul>\n<li>Odpowiadanie na Twoje pytania: mój prawnie uzasadniony interes w przedstawianiu mojej pracy osobom, które o nią pytają (art. 6 ust. 1 lit. f RODO).</li>\n<li>Kontakt zwrotny, gdy zostawisz swoje dane: działania podejmowane na Twoje żądanie przed ewentualnym zawarciem umowy (art. 6 ust. 1 lit. b RODO).</li>\n<li>Ochrona asystenta przed nadużyciami: mój prawnie uzasadniony interes w zapewnieniu bezpieczeństwa (art. 6 ust. 1 lit. f RODO).</li>\n<li>Ulepszanie odpowiedzi asystenta: mój prawnie uzasadniony interes (art. 6 ust. 1 lit. f RODO).</li>\n</ul>\n\n<h2>Odbiorcy danych</h2>\n<p>Dostawcy usług przetwarzający dane w moim imieniu: hosting i baza danych, usługi sieciowe i bezpieczeństwa, dostawca modelu AI (wyłącznie treść rozmowy), narzędzie do monitorowania i testów (wyłącznie treść rozmowy) oraz wysyłka e-maili.</p>\n<p>Niektórzy z nich mają siedzibę poza Europejskim Obszarem Gospodarczym, głównie w Stanach Zjednoczonych. Takie przekazania opierają się na programie ramowym w zakresie ochrony danych UE-USA (Data Privacy Framework) lub na standardowych klauzulach umownych zatwierdzonych przez Komisję Europejską.</p>\n\n<h2>Jak długo przechowuję dane</h2>\n<ul>\n<li>Rozmowy: 180 dni.</li>\n<li>Dane kontaktowe: tak długo, jak jest to potrzebne do kontaktu z Tobą.</li>\n<li>Kopie używane do monitorowania i testów: tak długo, jak jest to potrzebne do ulepszania asystenta.</li>\n</ul>\n\n<h2>Twoje prawa</h2>\n<p>Możesz zażądać dostępu do swoich danych, ich sprostowania, usunięcia, ograniczenia przetwarzania lub przekazania ich kopii, a także w każdej chwili wnieść sprzeciw wobec ich przetwarzania. Napisz na <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a>.</p>\n<p>Możesz też złożyć skargę do organu nadzorczego, np. do Prezesa UODO w Polsce (<a href=\"https://uodo.gov.pl\">uodo.gov.pl</a>).</p>"
    }
  },
  "terms": {
    "en": {
      "title": "Terms",
      "html": "<h2>1. Provider</h2>\n<div class=\"box\">\n<p><strong>Łukasz Bondarewicz</strong><br>ul. Spółdzielcza 9A/11, 78-400 Szczecinek, Poland<br>CEIDG, NIP 6731637301<br>Email: <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a></p>\n</div>\n\n<h2>2. Services</h2>\n<ul>\n<li>AI assistant: answers questions about my work, experience and availability, and can compare a job description with my profile.</li>\n<li>Contact form: lets you leave your name and email so I can reply.</li>\n</ul>\n\n<h2>3. Technical requirements</h2>\n<p>A device connected to the internet and a current web browser with JavaScript turned on.</p>\n\n<h2>4. Using the services</h2>\n<ul>\n<li>Use of the assistant starts when you send your first question and ends when you close the conversation or leave the site.</li>\n<li>You may not submit unlawful content.</li>\n</ul>\n\n<h2>5. Complaints</h2>\n<p>Email <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a>, describing the problem.</p>"
    },
    "pl": {
      "title": "Regulamin",
      "html": "<h2>1. Usługodawca</h2>\n<div class=\"box\">\n<p><strong>Łukasz Bondarewicz</strong><br>ul. Spółdzielcza 9A/11, 78-400 Szczecinek<br>CEIDG, NIP 6731637301<br>E-mail: <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a></p>\n</div>\n\n<h2>2. Usługi</h2>\n<ul>\n<li>Asystent AI: odpowiada na pytania o moją pracę, doświadczenie i dostępność oraz może porównać opis stanowiska z moim profilem.</li>\n<li>Formularz kontaktowy: pozwala zostawić imię i adres e-mail, żebym mógł odpowiedzieć.</li>\n</ul>\n\n<h2>3. Wymagania techniczne</h2>\n<p>Urządzenie z dostępem do internetu i aktualna przeglądarka internetowa z włączoną obsługą JavaScript.</p>\n\n<h2>4. Korzystanie z usług</h2>\n<ul>\n<li>Korzystanie z asystenta rozpoczyna się z chwilą wysłania pierwszego pytania i kończy po zamknięciu rozmowy lub opuszczeniu strony.</li>\n<li>Zakazane jest dostarczanie treści o charakterze bezprawnym.</li>\n</ul>\n\n<h2>5. Reklamacje</h2>\n<p>Napisz na <a href=\"mailto:hello@bondarewicz.com\">hello@bondarewicz.com</a>, opisując problem.</p>"
    }
  }
}
